require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254742063632',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0l6V1dVbVNjRDZYRW9zSlpQM2hxSFA0cm12cWQ5VnJnUnFBUWE2ZkZsVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT2djeElQWitZU201SjhwU1Y5ek41SFNxTG5aWExjcWJhbnJPb0I5QkdEND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXSlRVU1k1amx3RUl3RWdHUE5OQk1wVDltdXJYSHpPWGxNemt0TWh0M1ZBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJma1QxQmFodjJGUXFOMFU3YjBrUWo4Z2QwTzhlcGUzQmx3U1FBSWd4akNZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVIMlMxVE9CYkNORFpMbFVVWGVXM1FVNEEwRzhGcWE3bmZURlUvSE9ORzA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNDcisrUEw1ek9oaGZXbzM4Z1FSTHZOQVdBM3hkSm5lVDd4TUk0V1V3aFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia1A3U2htRzIrRGt0cEgzaUJBSTgyTTBOZVFTZ3dXbERONTh4US9MY2NrZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUGZkb3E2SXhSYWJBWmQ5dGZ3SGl6TUdpN3Q2TzZ6L2w3aXZUbjl6WGFVRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlqMTRTcWIwamxZMjRxbGluOTNYc3pzcUh6UGd0d3hOS2JMTnpWeXoyd0lZTzR3ZS9oaFZ5d2syQjBlTE5vSk1YMTNWaFB1SFRITlMzajdNdnpJMEJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE3LCJhZHZTZWNyZXRLZXkiOiJKRHE5OGJWMWVKY3pmTXNINjl0S3RUUTJZaDVHQzZ3dzBFbDBDdkVGSHE0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxNjE2MzkxNEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIxREE4NjI0QUM2QjBCMzZCMjcyRjgyMUZGMzY4RDc5MCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyMTE2Mzc3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTYxNjM5MTRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNUEyRTBEMEYzRUQxOTA0NkE4Q0QyNDM5Q0ZDMjkzODgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MjExNjM4Mn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiNzVDREdOTkoiLCJtZSI6eyJpZCI6IjI1NDcxNjE2MzkxNDoxNUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJOaWNjdXI0MjAiLCJsaWQiOiIxMDc3NjU1OTQ5MDY2ODc6MTVAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOclF0UDBFRUlqWnZNTUdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJmZ3d3am5SQld5L3ByRjRNbGlXdTljSTV2c1FIaFJHN3ZidU9oZ0lwZVdVPSIsImFjY291bnRTaWduYXR1cmUiOiJyRkw5MFZGMjB6L3FpTzJ0dWZpU1ZLOWQ2Y3Bic2VqeWlPTlREU0FqN2R5a2FNMTRsa3JjUWlXU3Q1REVBT3Z6eDFqaUNXSllaMEMrSU0wcnZyT3JCZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiOVN3WitFbCt5eG1VaWlVa2oxbjhEakJ0VGpJMTV5YjN2b3hvQ0I5OXRpVEw1RXZxSXI5aGxvT3ZNMFFEUUdvTVNGVWJ3dk84eCs2U09HL091Y0FqQkE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3MTYxNjM5MTQ6MTVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWDRNTUk1MFFWc3Y2YXhlREpZbHJ2WENPYjdFQjRVUnU3Mjdqb1lDS1hsbCJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUFnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUyMTE2MzczLCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTEJvIn0=',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID || null,

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
